### ISSUE TITLE
Do we need any other calibration before predicting MOS?

### ISSUE THREAD

**Issue by annahung31** [gabrielmittag/NISQA#10]
Hi, 

Thanks for the great works! 

I notice that #4 issue mentioned the volume of the input audio might affect the result. Is there any other calibration or pre-processing needs to be done for the wav files before applying run_predict.py to them?  To be more specifically, if I want to compare the MOS of speech audios recorded from different devices, is there any other calibration I need to apply?  For example, Active Speech Level adjustment in double-ended methods [1]. Thanks!

Reference:
[1] Section 3.2.1.4.: https://cdn.head-acoustics.com/fileadmin/data/global/Application-Notes/Telecom/3QUEST-Application-Note.pdf

**Comment by gabrielmittag** [comment]
Hi,

Generally, there is no pre-processing needed. However, the model will judge too quiet or too loud signals as degraded and it will result in a lower MOS score. The ideal volume is an active speech level (ASL) of -26dBo (same as for PESQ/POLQA). So if you want to compare different devices but want to neglect the difference in loudness it might be a good idea to normalize the signals.

The attached Figure shows the average MOS prediction (over multiple files) for different active speech level values. 
![image](https://user-images.githubusercontent.com/33029509/123823774-57939480-d8b2-11eb-8f51-b093c1c6efad.png)
