### ISSUE TITLE
Can the quality of front-end signal processing be evaluated?

### ISSUE THREAD

**Issue by zuowanbushiwo** [gabrielmittag/NISQA#14]
Hi
     Thank you very much for providing this project. 
     Can this project be used to evaluate the voice quality after front-end signal processing (AEC--Acoustic Echo Canceller, NS --noise suppression , AGC - automatic gain control)?
    Is it necessary to fine-tune the model? Do you know where to find some open source data sets  focused on speech enhancment / noise suppression ?
Thanks！

**Comment by gabrielmittag** [comment]
This model is not really focused on noise suppression and echo canceller. You could just try it out but it may be necessary to apply some finetuning.
