### ISSUE TITLE
modular version

### ISSUE THREAD

**Issue by MostafaAlaviyan** [gabrielmittag/NISQA#15]
hello
at first, thanks for your great and valuable work.
is it possible to provide a modular version of the NISQA?
or is it possible to use NISQA  as a module?
 best regards
@gabrielmittag

**Comment by gabrielmittag** [comment]
Hi, sorry for the late response. Yes, this is possible, have a look at the NISQA class in NISQA_lib.py. Let me know if you have any further questions but I'll close this issue for now.
