### ISSUE TITLE
Usage of PackedSequence class

### ISSUE THREAD

**Issue by Nesqulck** [gabrielmittag/NISQA#16]
In the framewise model, a new PackedSequence instance is generated from x_packed with x as the data argument (line 481 in nisqa_lib.py). However, this can lead to errors which tell you to never use PackedSequence but one of the helper functions instead, e.g. pack_padded_sequence. Since a PackedSequence is nothing more than a NamedTuple, you could circumvent this issue by using the _replace method:

This

        x = PackedSequence(
                x,
                batch_sizes = x_packed.batch_sizes,
                sorted_indices = x_packed.sorted_indices,
                unsorted_indices = x_packed.unsorted_indices
            )

becomes

        x = x_packed._replace(data=x)

A pretty minor thing but I ran into issues using PackedSequence directly before.

**Comment by gabrielmittag** [comment]
Thank you for the comment, that seems to be a nicer solution and I changed it in the code.
