### ISSUE TITLE
Bug in Alignment

### ISSUE THREAD

**Issue by Nesqulck** [gabrielmittag/NISQA#17]
There is a bug in Alignment in line 1267 when calculating the padding mask for the attention(scores) : https://github.com/gabrielmittag/NISQA/blob/2c8917f30c4e4bbca3a48e9852301f1e2480a741/nisqa/NISQA_lib.py#L1264-L1274

The padded elements of `att` should be set to `0` instead of `float(-Inf)`. `float(-Inf)` is only used if `att` would go into a softmax afterwards to achieve 0 attention at those places. However, in self.att(query, y) the softmax is already calculated for att (line 1273). Hence, it should be `att[~mask] = 0`. If I use the current implemetations, I get NaNs in ApplySoftAttention. If I use the proposed implemetation, everything works as intended

**Comment by gabrielmittag** [comment]
Thank you for pointing that out! I fixed it now by applying the softmax after the masking.
