### ISSUE TITLE
n_wins

### ISSUE THREAD

**Issue by adam-sabra** [gabrielmittag/NISQA#19]
hi, i have been going through the code and paper to get a thorough understanding of the internal mechanisms of the architecture. one thing that has eluded me is `n_wins` in the forward pass of many modules. 

can anyone give an insight as to what this `n_wins` is and what an expected input might be so i can simulate a forward pass with a random tensor?

thank you

**Comment by gabrielmittag** [comment]
`n_wins` is the number of spectrogram segments/windows, which depends on the duration of the input speech sample and the hop size. It comes from this function: https://github.com/gabrielmittag/NISQA/blob/47d8fead6ab62f62baf0b740a7d1781590a93c0d/nisqa/NISQA_lib.py#L2239

Basically, it is needed to make the model work with speech signals of different durations. You could also download the speech corpus and run the example scripts to get a better understanding of it.

**Comment by adam-sabra** [comment]
thank you Gabriel
