### ISSUE TITLE
About the NISQA_lib.py 

### ISSUE THREAD

**Issue by LCF2764** [gabrielmittag/NISQA#2]
Hi,
First of all thank you for your fantastic research!
I read the NISQA_lib.py code and found that the model you provided in this code is more like the model structure defined in "Quality Degradation Diagnosis for Voice Networks – Estimating the Perceived Noisiness, Coloration, and Discontinuity of Transmitted Speech", and not include the Per-frame Quality.
Will you continue to complete these codes in the future?
Thanks!

**Comment by gabrielmittag** [comment]
The code is now updated :)
