### ISSUE TITLE
Making .exe from anaconda

### ISSUE THREAD

**Issue by ZdennyPOZ** [gabrielmittag/NISQA#20]
Hey, I need to to make an .exe file from this project simply to make it more portable and make its size smaller. I tried to make one using pyinstaller but the result .exe is not working for me resulting in an error like this.
```
Traceback (most recent call last):
File "run_predict.py", line 5, in <module>
ModuleNotFoundError: No module named 'nisqa'
[4816] Failed to execute script 'run_predict' due to unhandled exception!
```
Is it  even possible to have an .exe of the prediction part of NISQA?

I have no problem of running it inside of anaconda but its really not what I want.

**Comment by gabrielmittag** [comment]
Hi, sorry I have not tried that. Maybe try google about using pyinstaller with pytorch.
