### ISSUE TITLE
Is it possible to use the model as a function?

### ISSUE THREAD

**Issue by chankl3579** [gabrielmittag/NISQA#24]
Thanks for sharing the repo. 
I have tried to use the model based on the guidelines in ```README``` and find it very useful. 
I am thinking is it possible to call this model as a function and return a scalar (the MOS) in python instead of using it only through command prompt. 
However, I am not good at programming, is there any advice where to start?

**Comment by gabrielmittag** [comment]
Hi, yes, just have a look at the run_predict.py and how the model is run within the script.

**Comment by JohnHerry** [comment]
Yes,   I am not familar with pandas dataframes, and there are too many arguemnts to run the whole scrip. I woud like a detailed  discription to the NISQA_lib.py  predict_dim function，  so that we can wrap a functaion myself.

    the NISQA_model.py  NISQA_lib.py are wrapped with dataset,  not good for split out a function to predict a single sample.
