### ISSUE TITLE
RuntimeError: Could not infer dtype of numpy.float32

### ISSUE THREAD

**Issue by YoungJay0612** [gabrielmittag/NISQA#26]
Hello, sorry to bother you. I have met a problem. I have configured the environment as described in the readme file, but the program is wrong when I run the run_predict_file.py, **RuntimeError: Could not infer dtype of numpy.float32**. Is the version of some libs are incorrectly? I have tried serveral versions of numpy, but it doesn't work and displays the same error.
Looking forward to your reply!

**Comment by gabrielmittag** [comment]
Hm I am not sure, could you share your wav file so I could test it? Or you could try one of the wav files from the NISQA dataset

**Comment by YoungJay0612** [comment]
[test.zip](https://github.com/gabrielmittag/NISQA/files/8945602/test.zip)
hello，thanks so much. the test.zip is  the wav file I used, you can have a try. And I will ttry to test the files from the NISQA dataset to confirm.

**Comment by YoungJay0612** [comment]
Here is the result of the DEMAND data DLIVING_16k chn01.wav. The result is the same.
![nisaq2](https://user-images.githubusercontent.com/20794414/174713092-f9e234d3-6b38-47e5-b1c8-7254d2ab22e1.jpg)

**Comment by gabrielmittag** [comment]
I just made a fresh install of the conda environment on an Ubuntu machine and cannot reproduce the error with the test.wav. Are you sure you are using the latest master branch? Did you install the environment with `conda env create -f env.yml`? Could you maybe double check which pytorch version you have installed in your environment?

**Comment by YoungJay0612** [comment]
As you mentioned, I have tried again. The version of the pytorch is as follows, and cannot find a version of 1.10.1 with pip install.
![nisaq3](https://user-images.githubusercontent.com/20794414/174728635-b038fd50-c86e-4919-97ac-b877f4c70361.jpg)

**Comment by YoungJay0612** [comment]
It's really unimaginable. I reinstall the torch==1.10.1 today as what I have did yesterday, and sucess in one fell swoop. Now It can be running with your example script. Thanks a lot for your patient reply. Now I can test it any way I want.

**Comment by gabrielmittag** [comment]
No worries, great that it works for you now
