### ISSUE TITLE
Could you tell me if the MOS rating is objective or subjective?

### ISSUE THREAD

**Issue by magicmans** [gabrielmittag/NISQA#33]
Could you please tell me if the MOS data in the NISQA Corpus is based on subjective MOS values from multi-person evaluations or on objective MOS values calculated using the ESPQ algorithm?

**Comment by gabrielmittag** [comment]
The MOS scores in the NISQA Corpus are subjective MOS values. Please also see the Wiki for more info, such as the number of ratings per file: https://github.com/gabrielmittag/NISQA/wiki/NISQA-Corpus

**Comment by magicmans** [comment]
Thank you for your response. Another question I have is: Can the NISQA model be trained and used for objective MOS prediction?

**Comment by gabrielmittag** [comment]
Yes, that's exactly what is trained for. Please check the Readme for more information

**Comment by magicmans** [comment]
thanks
