### ISSUE TITLE
CDUA device does not load the model

### ISSUE THREAD

**Issue by IamHussain503** [gabrielmittag/NISQA#39]
Hi,
It is an attempt to reach you about a a problem I face, the model does not load in to GPU while making inference. CPU is fast though , each file takes abour 1 second to complete, however this is not the behaviour what i want. I want it a little more faster. Can you please give me a hint. I have even used self.dev to cuda in NISQ_DIM, but model still goes to CPU. 
![image](https://github.com/gabrielmittag/NISQA/assets/33412791/cfeb437b-5d16-4a09-bdb1-62a571160684)

Thanks in advance!

**Comment by IamHussain503** [comment]
```
    nisqa = nisqaModel(args)
    # Print the device of the model
    print(" The parameters Device of the NISQA MODEL:  ",next(nisqa.model.parameters()).device)
    # Execute the prediction directly
    nisqa.predict()
```
The code gives me "cuda:0"   result of the print statement, but model inference goes to CPU. Thanks for your guidence.

**Comment by gabrielmittag** [comment]
it looks like it does go through the GPU, it's just that the model is relatively small so that the utilization is quite low. The CPU usage you are seeing is probably from the data preprocessing, such as computing Mel-specs
