### ISSUE TITLE
Interpertation of Different metrics 

### ISSUE THREAD

**Issue by IamHussain503** [gabrielmittag/NISQA#40]
Hi,
Thanks for your continued support and efforts in this subject. I wanted to ask a question different metric:
 'mos_pred':  1 worst 5 best  
  'noi_pred':   1 best 5 worst
  'dis_pred':    1 best 5 worst
  'col_pred':     1 best  5 worst
   loud_pred':    1 worst 5 best

Is this understanding right?
thanks in advance.

**Comment by gabrielmittag** [comment]
Hi, actually 1 is always the worst and 5 the best quality for the overall MOS and for the individual quality dimensions
