### ISSUE TITLE
upper bound and larger bound inconsistent with step sign

### ISSUE THREAD

**Issue by ghosthunterk** [gabrielmittag/NISQA#43]
Hi, I'm trying to batch predict on some speech CSVs, at first some audio segments are a bit lengthy which caused the problem of https://github.com/gabrielmittag/NISQA/issues/11, so I saved the new model as with new max as 5500: nisqa_tts_5500 and nisqa_all_5500, the models seem to predict fine until the problem of "upper bound and larger bound inconsistent with step sign" show up.

**Comment by gabrielmittag** [comment]
Hi sorry for replying late, let me know if this is still an issue and I will reopen the item
