### ISSUE TITLE
It seams slowly because of some functions running on CPU

### ISSUE THREAD

**Issue by troycjj** [gabrielmittag/NISQA#44]
y_hat_list = [ [model(xb.to(dev), n_wins.to(dev)).cpu().numpy(), yb.cpu().numpy()] for xb, yb, (idx, n_wins) in dl]

This function are running on cpu, cost my 60% CPU(8 core 16 processors R5 5700X)

I predict a 10 seconds audio on RTX4060TI used 0.26 seconds

cost in neural network less than 0.05 seconds
cost more than 0.2 seconds in DataLoader

**Comment by troycjj** [comment]
I found the reason!
get_librosa_melspec() function, Using Librosa to get melspec is slow,it can use audiotorch to instead, more than 2x faster

**Comment by gabrielmittag** [comment]
The computation of the Mel-Specs runs on CPU and the neural network is in fact quite small, so I think this is expected in a sense.
