### ISSUE TITLE
max window length error for most audio files

### ISSUE THREAD

**Issue by shivashankar6146** [gabrielmittag/NISQA#45]
I have started trying out this library on some of my audio files but I am facing the below error for most of my wav files

`ValueError: n_wins 2540 > max_length 1300 --- ok.wav. Increase max window length ms_max_segments!`

Could you please explain why this shall occur?

**Comment by asosawelford** [comment]
Hi, it seems like this issue is similar to #11 
From what I understand, the duration of the ok.wav audio exceds the default maximum. Maybe you could try shortening the audio, or overwrite the maximum length in the config file, with the caveat that's mentioned in the issue i've linked.

**Comment by gabrielmittag** [comment]
Thanks for explaining this, let me know if this should still be an issue.
