### ISSUE TITLE
mos_pred预测分数有些奇怪

### ISSUE THREAD

**Issue by gaox4793** [gabrielmittag/NISQA#48]
<img width="170" alt="1712055089638" src="https://github.com/gabrielmittag/NISQA/assets/150894898/7fb9f5b5-f655-4c25-ae3b-ec82ebd4b639">
<img width="470" alt="1712055259976" src="https://github.com/gabrielmittag/NISQA/assets/150894898/3d20c8b4-eff4-435b-99c4-408df9a6b17f">

这个评分似乎有些问题，我对原声音频和转换后的音频进行预测，歌曲原声的评分都低于3，但这是不可能的，而且在同一文件夹下进行预测时，分数惊人的接近，我想请问会有哪些原因造成这种情况，又该如何解决呢？

**Comment by gabrielmittag** [comment]
Sorry for replying late, let me know if this is still an issue and I will reopen the item.
