### ISSUE TITLE
MOS prediction during runtime

### ISSUE THREAD

**Issue by anuragkumar95** [gabrielmittag/NISQA#49]
I would like to use NISQA to predict MOS during runtime. Using `run_predict.py` is nice when I only have to predict MOS once. I would like to avoid loading NISQA model every time I want to calculate MOS of a wave file. My use case is something like

```
for i in (# of steps in the order of 10k):
    wav, sr = librosa.load(path)
    ...
    Do same changes to wav
    ....
    mos = NISQA(wav)
```

It would be really nice to have a method that loads the NISQA model once and allows me to pass wavfiles during runtime. Is there a way already to do this?

**Comment by gabrielmittag** [comment]
Hi yes you can run it on all files in a folder or on files given in a CSV file, have a look here: https://github.com/gabrielmittag/NISQA?tab=readme-ov-file#prediction
