### ISSUE TITLE
Can't download NISQA Corpus 

### ISSUE THREAD

**Issue by liushenme** [gabrielmittag/NISQA#5]
Hi,

I want to download the NISQA Corpus you just published. But the file I downloaded is 0 kb, and the download fails if I try again.
I think something is wrong about the download link. Could you check it？
Thank you.

Liu

**Comment by gabrielmittag** [comment]
Hi, 

Thanks for letting me know. The IT infrastructure of the TU Berlin is currently down. I added a mirror that should work.

Best, Gabriel
