### ISSUE TITLE
question about MOS_pred of synthetic speech

### ISSUE THREAD

**Issue by kay9012** [gabrielmittag/NISQA#52]
what's the difference of MOS_pred getted by nisqa.tar and nisqa_tts.tar? why the score getted by nisqa.tar is higher than that by nisqa_tts.tar?

**Comment by gabrielmittag** [comment]
nisqa_tts.tar is only thought to be applied on synthesized speech / text-to-speech samples, the corresponding paper can be found here: https://www.isca-speech.org/archive/Interspeech_2020/abstracts/2382.html

nisqa.tar is thought to be applied on transmitted speech, such as from audio calls. The paper can be found here: https://www.isca-archive.org/interspeech_2021/mittag21_interspeech.pdf
